/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


//import com.sun.glass.events.KeyEvent;
import java.awt.event.KeyEvent;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

public class levelLogin extends javax.swing.JFrame {

    Connection connect = null;
    ResultSet res = null;
    PreparedStatement pre = null;
    
    /**
     * Creates new form levelLogin
     */
    public levelLogin() {
        initComponents();
        Toolkit tool = getToolkit();
        Dimension size = tool.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,
                size.height/2 - getHeight()/2);       
        date();
    }
    
    public void date(){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH); 
        date.setText("Date: "+day+"/"+(month+1)+"/"+year);           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        level = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmdlogin = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 400));
        setMinimumSize(new java.awt.Dimension(640, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("กรุณาใส่ username และ password และเลือกสถานะผู้ใช้ เพื่อเข้าสู่ระบบ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 590, 60);

        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(username);
        username.setBounds(230, 90, 190, 40);
        getContentPane().add(password);
        password.setBounds(230, 150, 190, 40);

        level.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "User", " " }));
        getContentPane().add(level);
        level.setBounds(230, 210, 190, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 150, 90, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Level");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 210, 50, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 90, 100, 40);

        cmdlogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmdlogin.setText("Login");
        cmdlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdloginActionPerformed(evt);
            }
        });
        getContentPane().add(cmdlogin);
        cmdlogin.setBounds(260, 270, 130, 40);

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(date);
        date.setBounds(500, 320, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATE:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(450, 320, 49, 30);

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/bk.jpg"))); // NOI18N
        pic.setFocusable(false);
        getContentPane().add(pic);
        pic.setBounds(0, 0, 640, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdloginActionPerformed
        
        if(username.getText().equals("")){
        
            JOptionPane.showMessageDialog(null, "กรุณาใส่ username");
            
        }
        else if(password.getText().equals("")){
            JOptionPane.showMessageDialog(null, "กรุณาใส่ password");
           
        }
        else{
            String sql = "SELECT * level,username,password from"+
                    "employees_info.levellogin where"
                    +"username =? and password =? and level =? ";
            try {
                int count = 0;
                pre= connect.prepareStatement(sql);
                pre.setString(2, username.getText());
                pre.setString(3, password.getText());
                pre.setString(4,level.getSelectedItem().toString());
                res = pre.executeQuery();
                
                while (res.next()) {
                    String  id = res.getString("idlevelLogin");
                    //Database.Emp.empID=id;
                    count=count+1;
                }
                String access=(level.getSelectedItem().toString());
                if(access=="Administrator"){
                    if(count==1){
                        JOptionPane.showMessageDialog(null, "Success");
                        this.dispose();
                    }
                }
                
            } catch (Exception e) {
            }
        }
        
        
    }//GEN-LAST:event_cmdloginActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(levelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(levelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(levelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(levelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new levelLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdlogin;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel pic;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
