/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.Connections;
import java.awt.event.KeyEvent;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
public class login extends javax.swing.JFrame {

    
    Database.Connections connect = new Database.Connections();
    Connection connects = connect.get_Connections();
    ResultSet res = null;
    PreparedStatement pre = null;
    
    
    public login() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        date();
    }
    
    public void date (){
        
        Calendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        txt_date.setText((month+1)+"/"+day+"/"+year);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cmd_Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        selectlevel = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        txt_date = new javax.swing.JMenu();
        command = new javax.swing.JMenu();
        ctrlQ = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 340));
        setMinimumSize(new java.awt.Dimension(400, 340));
        setPreferredSize(new java.awt.Dimension(400, 340));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        cmd_Login.setText("Login");
        cmd_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_LoginActionPerformed(evt);
            }
        });
        cmd_Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmd_LoginKeyPressed(evt);
            }
        });
        jPanel2.add(cmd_Login);
        cmd_Login.setBounds(210, 190, 70, 30);

        jLabel1.setText("Username:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(60, 80, 70, 18);

        jLabel2.setText("Password:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 120, 70, 18);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Please enter your username and password");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 40, 263, 14);
        jPanel2.add(username);
        username.setBounds(150, 70, 132, 30);

        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        jPanel2.add(password);
        password.setBounds(150, 110, 130, 30);

        selectlevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "User" }));
        selectlevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectlevelActionPerformed(evt);
            }
        });
        jPanel2.add(selectlevel);
        selectlevel.setBounds(150, 150, 130, 30);

        jLabel3.setText("Select Position:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 160, 100, 18);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 310);

        Menu.add(jMenu3);

        txt_date.setText("Date");
        Menu.add(txt_date);

        command.setText("File");

        ctrlQ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        ctrlQ.setText("Exit");
        ctrlQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrlQActionPerformed(evt);
            }
        });
        command.add(ctrlQ);

        Menu.add(command);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctrlQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrlQActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ctrlQActionPerformed

    private void cmd_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_LoginActionPerformed
       if(username.getText().equals("")){
           JOptionPane.showMessageDialog(null, 
                   "Usesrname must not Empty");
        }
       else if(password.getText().equals("")){
           JOptionPane.showMessageDialog(null, 
                   "Password must not Empty");
       }
       else{
           String sql = 
                   "SELECT username,password,userLevel from employees_info.emp where username =? and password = ? and userLevel = ?";
           try {
               int count = 0;
               pre=connects.prepareStatement(sql);
               pre.setString(1, username.getText());
               pre.setString(2, password.getText());
               pre.setString(3, 
                       selectlevel.getSelectedItem().toString());
               res=pre.executeQuery();
               
               while (res.next()) {
                   String id = res.getString(1);
                   Database.Emp.empID = id; 
                   count=count+1;
               }
               String access = (selectlevel.getSelectedItem().toString());
               if(access=="Admin"){
                   if(count ==1){
                       JOptionPane.showMessageDialog(null, "success");
                       MainMenu main = new MainMenu();
                       main.setVisible(true);
                       //this.dispose();
                       Date date = GregorianCalendar
                               .getInstance().getTime();
                       DateFormat format = DateFormat.getDateInstance();
                       String dateE = format.format(date);
                       Date d= new Date();
                       SimpleDateFormat time = 
                               new SimpleDateFormat("HH:mm:ss");
                       String timeSt = time.format(d);
                       
                       String auditdate=dateE;
                       String audittime=timeSt;
                       String statusC= "login";
                       //String statusA="absen";
                       
                       String value = Database.Emp.empID;
                       String login = "insert into employees_info.audit (Eid,date,time,status) values ('"+value+"','"+auditdate+"','"+audittime+"','"+statusC+"')";
                              // +(value+","+auditdate+","+audittime+","+statusC);
                       //('"+value+"','"+value0+" / "+values+"','Logged in')";
                       //"insert into Audit (emp_id,date,status) values ('"+value+"','"+value0+" / "+values+"','Logged in')"
                               
                       pre=connects.prepareStatement(login);
                       pre.execute();
                       this.dispose();                    
                   }
                   else if(count>1){
                       JOptionPane.showMessageDialog(null,"Duplicate Username "
                               + "or Password Access denied" );
                       
                   }
                   else{
                       JOptionPane.showMessageDialog(null,
                       "Username and Password is not correct");
                   }                  
               }
               else if(access=="User"){
                   if(count==1){
                       JOptionPane.showMessageDialog(null, "success");
                       MainMenu main = new MainMenu();
                       main.setVisible(true);
                       
                       Date date = GregorianCalendar
                               .getInstance().getTime();
                       DateFormat format = DateFormat.getDateInstance();
                       String dateE = format.format(date);
                       Date d= new Date();
                       SimpleDateFormat time = 
                               new SimpleDateFormat("HH:mm:ss");
                       String timeSt = time.format(d);
                       
                       String auditdate=dateE;
                       String audittime=timeSt;
                       String statusC= "login";
                       //String statusA="absen";
                       
                       String value = Database.Emp.empID;
                       String login = "insert into employees_info.audit (Eid,date,time,status) values ('"+value+"','"+auditdate+"','"+audittime+"','"+statusC+"')";
                       pre=connects.prepareStatement(login);
                       pre.execute();
                       this.dispose();          
                   }
                   else{
                        JOptionPane.showMessageDialog(null,
                       "Username and Password is not correct"); 
                    }                  
               }               
           } 
           catch (Exception e) {
               JOptionPane.showMessageDialog(null, e);
            }
           finally {
            
            try{
                res.close();
                pre.close(); 
                setVisible(false);
            }
            catch(Exception e){               
            }
          }           
       }      
    }//GEN-LAST:event_cmd_LoginActionPerformed

    private void cmd_LoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmd_LoginKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmd_LoginKeyPressed

    private void selectlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectlevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectlevelActionPerformed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           String sql = "SELECT username,password,userLevel from employees_info.emp where username =? and password = ? and userLevel = ?";
           try {
               int count = 0;
               pre=connects.prepareStatement(sql);
               pre.setString(1, username.getText());
               pre.setString(2, password.getText());
               pre.setString(3, 
                       selectlevel.getSelectedItem().toString());
               res=pre.executeQuery();
               
               while (res.next()) {
                   String id = res.getString(1);
                   Database.Emp.empID = id; 
                   count=count+1;
               }
               String access = (selectlevel.getSelectedItem().toString());
               if(access=="Admin"){
                   if(count ==1){
                       JOptionPane.showMessageDialog(null, "success");
                       MainMenu main = new MainMenu();
                       main.setVisible(true);
                       //this.dispose();
                       Date date = GregorianCalendar
                               .getInstance().getTime();
                       DateFormat format = DateFormat.getDateInstance();
                       String dateE = format.format(date);
                       Date d= new Date();
                       SimpleDateFormat time = 
                               new SimpleDateFormat("HH:mm:ss");
                       String timeSt = time.format(d);
                       
                       String auditdate=dateE;
                       String audittime=timeSt;
                       String statusC= "login";
                       //String statusA="absen";
                       
                       String value = Database.Emp.empID;
                       //System.out.println(value);
                       String login = "insert into employees_info.audit (Eid,date,time,status) values ('"+value+"','"+auditdate+"','"+audittime+"','"+statusC+"')";
                       pre=connects.prepareStatement(login);
                       pre.execute();
                       this.dispose();                    
                   }
                   else if(count>1){
                       JOptionPane.showMessageDialog(null,"Duplicate Username "
                               + "or Password Access denied" );                       
                   }
                   else{
                       JOptionPane.showMessageDialog(null,
                       "Username and Password is not correct");
                   }                  
               }
               else if(access=="User"){
                   if(count==1){
                       JOptionPane.showMessageDialog(null, "success");
                       MainMenu main = new MainMenu();
                       main.setVisible(true);
                       
                       Date date = GregorianCalendar
                               .getInstance().getTime();
                       DateFormat format = DateFormat.getDateInstance();
                       String dateE = format.format(date);
                       Date d= new Date();
                       SimpleDateFormat time = 
                               new SimpleDateFormat("HH:mm:ss");
                       String timeSt = time.format(d);
                       
                       String auditdate=dateE;
                       String audittime=timeSt;
                       String statusC= "login";
                       //String statusA="absen";
                       
                       String value = Database.Emp.empID;
                       String login = "insert into employees_info.audit (Eid,date,time,status) values ('"+value+"','"+auditdate+"','"+audittime+"','"+statusC+"')";
                       pre=connects.prepareStatement(login);
                       pre.execute();
                       this.dispose();          
                   }
                   else{
                        JOptionPane.showMessageDialog(null,
                       "Username and Password is not correct"); 
                    }                  
               }               
           } 
           catch (Exception e) {
               JOptionPane.showMessageDialog(null, e);
            }
           finally {
            
            try{
                res.close();
                pre.close();
                setVisible(false);
            }
            catch(Exception e){               
            }
          }
       }      
    }//GEN-LAST:event_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton cmd_Login;
    private javax.swing.JMenu command;
    private javax.swing.JMenuItem ctrlQ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox selectlevel;
    private javax.swing.JMenu txt_date;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
