/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import com.mysql.jdbc.Statement;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
//import net.proteanit.sql.DbUtils;
public class Users extends javax.swing.JFrame {

    Database.Connections connect = new Database.Connections();
    Connection con = connect.get_Connections();
    ResultSet res = null;
    PreparedStatement pre = null;
    public Users() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        Fill();
    }
    
    private void Fill(){
    
        try {
            String sql = "select Eid,username,password from employees_info.Users ";
            pre=con.prepareStatement(sql);
            res=pre.executeQuery();
            while (res.next()) {
                String name = res.getString("username");
                level.addItem(name);
                                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try {
                res.close();
                pre.close();
            } catch (Exception e) {
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        level = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        del = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 330));
        setMinimumSize(new java.awt.Dimension(500, 330));
        setPreferredSize(new java.awt.Dimension(500, 330));
        setResizable(false);
        getContentPane().setLayout(null);

        level.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Users" }));
        getContentPane().add(level);
        level.setBounds(130, 80, 200, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Register");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 30, 110, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Select User");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 70, 15);
        getContentPane().add(id);
        id.setBounds(130, 120, 200, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 130, 50, 15);
        getContentPane().add(dep);
        dep.setBounds(130, 160, 200, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Department");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 80, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Username");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 210, 80, 15);
        getContentPane().add(username);
        username.setBounds(130, 200, 200, 30);
        getContentPane().add(pass);
        pass.setBounds(130, 240, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 250, 70, 15);

        clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clear.setText("Claer");
        getContentPane().add(clear);
        clear.setBounds(360, 200, 100, 30);

        add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add.setText("Add ");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(360, 80, 100, 30);

        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setText("Update ");
        getContentPane().add(update);
        update.setBounds(360, 120, 100, 30);

        del.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        del.setText("Delete");
        getContentPane().add(del);
        del.setBounds(360, 160, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        int p = JOptionPane.showConfirmDialog(null, 
                "ต้องกาารที่จะเพิ่มข้อมูลเจ้าใน records หรือไม่","เพิ่ม records"
                ,JOptionPane.YES_NO_OPTION);
        if(p==0){
            try {
                String sql = "insert into Users "
                        + "(Eid,username,password,department,level)"
                        + " values(?,?,?,?,?) ";
                pre=con.prepareStatement(sql);
                pre.setString(1, id.getText());
                pre.setString(2, username.getText());
                pre.setString(3, pass.getText());
                pre.setString(4, dep.getText());
                String selected = (String) level.getSelectedItem();
                pre.setString(5,selected);
                pre.execute();
                JOptionPane.showMessageDialog(null, 
                        "data have been saved");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            finally{
                try {
                    res.close();
                    pre.close();
                } catch (Exception e) {
                }
            }           
        }
        Fill();
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton clear;
    private javax.swing.JButton del;
    private javax.swing.JTextField dep;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JTextField pass;
    private javax.swing.JButton update;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
